sonar.projectKey=dcanosu_aws-lab
sonar.organization=dcanosu
sonar.host.url=https://sonarcloud.io

sonar.terraform.provider.aws.version=5.0

sonar.sources=.
sonar.exclusions=**/*.tfstate, **/*.tfplan, .github/**, terraform/.terraform/**
