plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Name: 
    - "app-asg"
  instance-state-name:  
    - "running"

keyed_groups:
  - key: tags
    prefix: aws_tags
    separator: "_"

hostnames:
  # - public-ip-address
  - dns-name
compose:
  # ansible_host: public_ip_address
  ansible_hist: dns-name