name: "Code Quality"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Sonar Token from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SONAR_TOKEN, aws-lab/sonar-token
            GITHUB_TOKEN, aws-lab/scm-access
          parse-json-secrets: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

      - name: Get Sonar Token from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SONAR_VAR, aws-lab/sonar-token
            GH_VAR, aws-lab/scm-access
          parse-json-secrets: true

      - name: 🔍 Debug Variable Names
        # Este comando listará todas las variables que empiezan por SONAR o GH
        # No mostrará los valores (GitHub los protege con ***), pero sí los NOMBRES
        run: |
          echo "Buscando nombres de variables inyectadas por AWS:"
          env | grep -E "SONAR_VAR|GH_VAR" | cut -d'=' -f1
        shell: bash

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          # Si el debug de arriba dice 'SONAR_VAR_SONAR_TOKEN', úsala así:
          SONAR_TOKEN: ${{ env.SONAR_VAR_SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ env.GH_VAR_GH_TOKEN }}