name: Deploy App Only

on:
  push:
    paths:
      - 'ansible/roles/docker/files/index.html'

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: 🔑 Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: 📦 Inject AWS Tools into Ansible
        run: |
          # Usamos pipx para que Ansible encuentre Boto3 al instante
          pipx inject ansible-core boto3 botocore --force
          ansible-galaxy collection install amazon.aws

      - name: 🛰️ Run Ansible (Full sync)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_DEPRECATION_WARNINGS: "False"
        run: |
          # Quitamos --tags para que Ansible sincronice todo el estado
          ansible-playbook -i ansible/inventories/aws_ec2.yaml \
            ansible/site.yaml \
            -u ec2-user \
            --private-key ~/.ssh/id_rsa \
            -e "asg_name=${{ secrets.ASG_NAME }}"