name: "Terraform Destroy"

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm infrastructure deletion'
        required: true
        default: 'NO'

permissions:
  contents: read
  id-token: write

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
            echo "Destruction NOT confirmed. Exiting..."
            exit 1
          fi

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=terraform-state-app-tf" \
            -backend-config="key=prod/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
